<a href="https://colab.research.google.com/github/monisakhtar/ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [4]:
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
# When you use numpy.array to define a new array, you should consider the dtype of the elements in the array, which can be specified explicitly.
np.array([1, 2], dtype=int)

array([1, 2])

In [6]:
# Creating array using arange function
np.arange(1, 5)

array([1, 2, 3, 4])

In [7]:
# We can even specify step size and dtype
np.arange(0, 5, 1, dtype=int)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
# However, when dealing with floats, the exact number of elements in the array is not always predictable. For example, consider this:
print(np.arange(0, 5/3, 1/3)) # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.arange(0, 5/3, 0.333333333))
print(np.arange(0, 5/3, 0.333333334))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333334]


`np.linspace`

For this reason, it is generally preferable to use the `linspace` function instead of `arange` when working with floats. The `linspace` function returns an array containing a specific number of points evenly distributed between two values (note that the maximum value is *included*, contrary to `arange`):

In [10]:
print(np.linspace(0, 5/3, 6))
print(np.linspace(1, 2, 5))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[1.   1.25 1.5  1.75 2.  ]


In [11]:
# The zeros function creates an array containing any number of zeros:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
# The ones function creates an array containing any number of ones:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# The full function takes dimention and a value and fills each element with the value
np.full((2,3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [16]:
# The empty() function, on the other hand, will simply allocate memory without assigning it any values. This means that the contents of an empty array will be whatever happened to be in memory at the time.
np.empty((2,3))

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

## Some vocabulary

* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the 3x4 matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (e.g. 3*4=12)

In [17]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
a.shape

(3, 4)

In [19]:
a.size

12

In [20]:
type(a)

numpy.ndarray

In [21]:
# We can also create an N-dimensional array of arbitrary rank. For example, here's a 3D array (rank=3), with shape (2,3,4):
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Random Module

rand()

*   Create an array of specified shape and fills it with random value as per uniform distribution.
*   Values will be in the [0, 1) interval



In [22]:
np.random.rand(2,3)

array([[0.67282932, 0.27507864, 0.0272095 ],
       [0.09263586, 0.64504497, 0.01406153]])

In [23]:
# Returns a random value between [0, 1)
np.random.rand()

0.5685755511975646

rand()

*   Create an array of specified shape and fills it with random value as per standard normal distribution.

In [24]:
np.random.randn(2,3)

array([[-0.18496443,  0.02795609,  1.12024406],
       [ 1.82149084,  1.13193494,  0.38156765]])

In [25]:
np.random.randn()

-0.41474138558065365

ranf()

*   Create an array of specified shape and fills it with random float value .
*   Values will be in the [0, 1) interval

In [26]:
np.random.ranf(3)

array([0.51591667, 0.46967918, 0.4434583 ])

randnint()

*   Create an array of specified shape and fills it with random integers from low to high
*   Values will be in the [low, high) interval
*   If high is not mentioned interval will be [0, low)

In [27]:
# Low and high are mentioned
np.random.randint(2,7)

6

In [28]:
# Low, high, size is mentioned
np.random.randint(2, 7, 3)

array([3, 6, 5])

In [29]:
np.random.randint(2,7, (2,3))

array([[5, 6, 5],
       [3, 2, 3]])

In [30]:
# only low is mentioned
np.random.randint(7)

6

In [31]:
a = np.arange(4)
a

array([0, 1, 2, 3])

# type() and dtype

In [32]:
type(a)

numpy.ndarray

In [33]:
a.dtype

dtype('int64')

In [34]:
b = np.array([1,2,3], dtype = complex)
b

array([1.+0.j, 2.+0.j, 3.+0.j])

In [35]:
type(b)

numpy.ndarray

In [36]:
b.dtype

dtype('complex128')

When you are creating an array, the dtype that is automatically selected will always be that of the least precise element.

In [37]:
a = np.array([6, 28.0, 496, 8128])
a.dtype

dtype('float64')

We can always force an array to have a given data type by passing dtype=<type> as a keyword argument to the array creation function.

In [38]:
a = np.array([6, 28.56, 496, 8128], dtype=int)
a.dtype

dtype('int64')

In [39]:
a

array([   6,   28,  496, 8128])

# Slicing

In [41]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [42]:
# Return 1, 2, 3
a[1:4]

array([1, 2, 3])

In [43]:
# Return from something till end of array
a[4:]

array([4, 5, 6, 7])

In [44]:
# Return negative slices eg- Return 5,6
a[-3:-1]

array([5, 6])

In [49]:
# Return in steps
a[1:5]    # Return 1,2,3,4

array([1, 2, 3, 4])

In [50]:
a[1:6:2]  # Return in steps of 2

array([1, 3, 5])

In [51]:
# Return in steps of 2 on the whole array
a[::2]

array([0, 2, 4, 6])

In [53]:
# Return a reverse slice
a[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [55]:
# Return reverse slice in steps of 2
a[::-2]

array([7, 5, 3, 1])

In [57]:
# Slicing a 2D array
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
# Pulling out a single item
b[1,2]

7

In [60]:
# slicing a 2D array
b[0:1, 1:3]

array([[2, 3]])

In [61]:
# slicing from both rows
b[0:2, 1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [62]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
a = a.reshape(4,4)

In [68]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
a[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [70]:
a[2::-1, :3]

array([[ 8,  9, 10],
       [ 4,  5,  6],
       [ 0,  1,  2]])

Views

That slice arrays are views means that modifications to their elements are reflected back in the original arrays. If you have two arrays a and b, where b is a slice of a, then you can tell that b is a view if its base is a. Furthermore, changes to the contents of either a or b will also affect the other array.

In [79]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [80]:
# Creating a view b from slicing a
b = a[1::2]
b

array([1, 3, 5])

In [81]:
# Changing an element of b 
b[1] = 42

In [82]:
# Change in b is reflected in a as well 
a

array([ 0,  1,  2, 42,  4,  5])

In [83]:
b.base is a

True

In [84]:
# If you truly want a copy of a slice of an array, you can always create a new array from the slice
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
b = np.array(a[1::11])
b

array([ 1, 12])